create table "DWH_COMMON"."DWH_METADATA"."DWH_APP_TABLE_META"(
FILENAME VARCHAR,
SF_TABLE VARCHAR,
FILE_FORMAT VARCHAR,
APPLICATION_NAME VARCHAR,
APPLICATION_ID NUMBER,
ACTIVE_FLAG VARCHAR(1)
)
;

CREATE TABLE 
