CREATE TABLE "csv11_001" (
	"ID" DECIMAL(38, 0) NOT NULL, 
	"NAME" VARCHAR NOT NULL, 
	"ADDRESS" VARCHAR NOT NULL
);
CREATE TABLE "csv12_002" (
	"ID" DECIMAL(38, 0) NOT NULL, 
	"NAME" VARCHAR NOT NULL, 
	"ADDRESS" VARCHAR NOT NULL
);
CREATE TABLE "csv13_025" (
	"ID" DECIMAL(38, 0) NOT NULL, 
	"NAME" VARCHAR NOT NULL, 
	"ADDRESS" VARCHAR NOT NULL
);
